### ISSUE TITLE
Device Agent should automatically re-establish Editor Tunnel after a restart

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/device-agent#147]
Currently the device agent does not persist the fact the editor tunnel should be active. This means after a restart of the agent, the platform has to re-notify the agent to establish the tunnel.

As part of the work to improve the overall reliability of the tunnel (as far as end users are concerned), it would be sensible for the agent to recover the tunnel after a restart if needed.

The best way will be for the expected tunnel state to be included in the response of the checkin call. When the device does its initial checkin, it will find out the tunnel should be running and it can establish it.

The existing MQTT commands to enable/disable will still be used to trigger the tunnel without waiting for the device to call home.

**Comment by knolleary** [comment]
@MarianRaphael this item relates to overall reliability and resilience of the Device Editor. I'd like to get it scheduled soon.

**Comment by Steve-Mcl** [comment]
PR #147 raised.  Local testing is 100% successful even after extended (1h) wait between stop/start of device agent. 

Potential Follow up task:  Since the device essentially disconnects from the platform, browsing to the Developer Mode page reveals a tunnel status of "not connected".  However, this page is NOT polled so will NOT show "not connected" if the page is open when the device is shutdown.  Similarly, if Developer Mode page is visited while the device is powered off, it will continue to show "not connected" even though it is.  NOTE: This is nothing new

### Verification criteria

1st, connect a device and enable developer mode and verify editor access, then:
- [ ] kill device agent
- [ ] refresh editor page & see the "device unavailable message"
- [ ] visit/refresh Device's "Developer Mode page" on FF - should show "not connected"
- [ ] start device agent
- [ ] refresh editor page - should connect / display editor
- [ ] visit/refresh Device's "Developer Mode page" on FF - should NOT show "not connected"

**Comment by hardillb** [comment]
Verified with local
